# Generated by Django 2.2.12 on 2020-05-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200525_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hghg',
        ),
    ]
